const pikachu = require('../screens/images/001.png');
const ivysaur = require('../screens/images/002.png');
const slowpoke = require('../screens/images/003.png');
const charmanda = require('../screens/images/004.png');
const charmeleon = require('../screens/images/005.png');
const charizard = require('../screens/images/006.png');
const squirtle = require('../screens/images/007.png');
const warturtle = require('../screens/images/008.png');
const mewtwo = require('../screens/images/009.png');
const chansey = require('../screens/images/010.png');
const burbasaur = require('../screens/images/011.png');
const alakazam = require('../screens/images/012.png');
const wigglytuff = require('../screens/images/013.png');
const vileplume = require('../screens/images/014.png');
const psyduck = require('../screens/images/015.png');
const arcanine = require('../screens/images/016.png');
const poliwhirl = require('../screens/images/017.png');
const chikorita = require('../screens/images/018.png');
const rapidash = require('../screens/images/019.png');
const gyarados = require('../screens/images/020.png');

const mechanical = require('./images/3me.jpg');
const aerospace = require('./images/aerospace.jpg');
const appliedphysics = require('./images/appliedphysics.jpg');
const appliedsciences = require('./images/appliedsciences.jpg');
const architecture = require('./images/architecture.jpg');
const aula = require('./images/aula.jpg');
const biotechnology = require('./images/biotechnology.jpg');
const chemical = require('./images/chemical.jpg');
const civil = require('./images/civil.jpg');
const culture = require('./images/culture.jpg');
const education = require('./images/education.jpg');
const ewi = require('./images/ewi.jpg');
const facility = require('./images/facility.jpg');
const fellowship = require('./images/fellowship.jpg');
const io = require('./images/io.jpeg');
const library = require('./images/library.jpg');
const physical = require('./images/physicalandchemical.jpg');
const process = require('./images/processandenergy.jpg');
const sport = require('./images/sport.jpg');
const tpm = require('./images/tpm.jpg');

const event01 = require('./images/event01.jpg');

export const achievements = [
  {
    achievementName: 'Newbie',
    image: pikachu,
    isUnlocked: true,
    feedback:
      'Great! You have unlocked your first sticker! Explore the campus to collect them all!',
  },
  {
    type: 'site',
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2812,
    minor: 2735,
    achievementName: 'Adventurer',
    image: chansey,
    isUnlocked: false,
    instruction:
      'Visit Electrical Engineering, Mathematics and Computer Sciences to unlock this sticker!',
    feedback:
      'Congratulations! You are now an adventurer! Do not wait! Continue to collect them all!',
    address: {
      postcode: '2628 CD',
      straat: 'Mekelweg',
      huisnummer: '4',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '51.99903', '@lat': '4.37323' },
    name: 'Electrical Engineering, Mathematics and Computer Sciences',
    locatieCode: '36',
    picture: ewi,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    type: 'event',
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 258,
    minor: 772,
    achievementName: 'Explorer',
    image: gyarados,
    isUnlocked: false,
    instruction: 'You can unlock this sticker if you attend Latitud Presents on time!',
    feedback:
      'Congratulations! You are now an explorer! Do not wait! Continue to collect them all!!',
    address: {
      postcode: '2629 HS',
      straat: 'Kluyverweg',
      huisnummer: '5',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '51.99065', '@lat': '4.37756' },
    name: 'Latitud Presents',
    start: 'Sunday, July 16, 2017 7:30 PM',
    end: 'Sunday, July 16, 2017 10:00 PM',
    cost: '8.00 euro',
    locatieCode: '66',
    picture: event01,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
];

// export const achievements = [
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0', // indication for the whole campus region
//     major: 772, // indication for the building
//     minor: 258, // indication for different corners in the same building
//     achievementName: 'Newbie',
//     image: pikachu,
//     isUnlocked: true,
//     instruction: 'Visit Aula Conference Center to unlock this sticker!',
//     feedback: 'Yay! You unlocked your first sticker! Explore the campus to collect them all! ',
//     address: {
//       postcode: '2628 CC',
//       straat: 'Mekelweg',
//       huisnummer: '5',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '52.0021', '@lat': '4.37325' },
//     name: 'Aula Conference Centre',
//     locatieCode: '20',
//     picture: aula,
//     info:
//       'De combinatie van een Technische Universiteit, een gezellige oude stad, een goede bereikbaarheid en een perfecte outillage, maakt het Aula Congrescentrum een uiterst geschikte locatie voor congressen en andere wetenschappelijke of culturele bijeenkomsten.Het Aula Congrescentrum beschikt over 12 zalen van verschillende grootte, geschikt voor 10 tot 1200 personen. De zeer ruime Foyer, de verschillende vides en de entreehal met ontvangstbalie, maken het Aula Congrescentrum tot een unieke locatie.',
//   },
//   {
//     type: 'event',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 258,
//     minor: 772,
//     achievementName: 'Adventurer',
//     image: gyarados,
//     isUnlocked: false,
//     instruction: 'You can unlock this stiker if you arrive in the event location on time!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2629 HS',
//       straat: 'Kluyverweg',
//       huisnummer: '5',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '51.99065', '@lat': '4.37756' },
//     name: 'Latitud Presents',
//     start: '21:00 on Friday, 16/06/2017',
//     end: '03:00 on Sartuday, 17/06/2017',
//     cost: '8.00 euro',
//     locatieCode: '66',
//     picture: fellowship,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Explorer',
//     image: ivysaur,
//     isUnlocked: false,
//     instruction: 'Visit Achitecture and the Built Environment to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     name: 'Architecture and the Built Environment',
//     address: {
//       postcode: '2628 BL',
//       straat: 'Julianalaan',
//       huisnummer: '132-134',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '52.005696', '@lat': '4.370439' },
//     locatieCode: '08',
//     picture: architecture,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Local',
//     image: slowpoke,
//     isUnlocked: false,
//     instruction: 'Visit Applied Science to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2629 HZ',
//       straat: 'Van Der Maasweg',
//       huisnummer: '9',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '4.379922', '@lat': '51.989124' },
//     name: 'Applied Sciences',
//     locatieCode: '58',
//     picture: appliedsciences,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Century Club',
//     image: charmanda,
//     isUnlocked: false,
//     instruction: 'Visit Aerospace Engineering to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2629 HS',
//       straat: 'Kluyverweg',
//       huisnummer: '1',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '51.989923', '@lat': '4.375549' },
//     name: 'Aerospace Engineering',
//     locatieCode: '62',
//     picture: aerospace,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Tasty',
//     image: charmeleon,
//     isUnlocked: false,
//     instruction: 'Visit Applied Physics to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2628 CJ',
//       straat: 'Lorentzweg',
//       huisnummer: '1',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '52.000912', '@lat': '4.37402' },
//     name: 'Applied Physics',
//     locatieCode: '22',
//     picture: appliedphysics,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Foodie',
//     image: charizard,
//     isUnlocked: false,
//     instruction: 'Visit Biotechnology to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2628 BC',
//       straat: 'Julianalaan',
//       huisnummer: '67',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '52.00856', '@lat': '4.37129' },
//     name: 'Biotechnology',
//     locatieCode: '05',
//     picture: biotechnology,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Commuter',
//     image: squirtle,
//     isUnlocked: false,
//     instruction: 'Visit Civil Engineering and Geosciences to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2628 CN',
//       straat: 'Stevinweg',
//       huisnummer: '1',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '51.99913', '@lat': '4.37595' },
//     name: 'Civil Engineering and Geosciences',
//     locatieCode: '23',
//     picture: civil,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Do Not Disturb',
//     image: warturtle,
//     isUnlocked: false,
//     instruction: 'Visit Culture Center to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2628 CD',
//       straat: 'Mekelweg',
//       huisnummer: '10',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '51.9954', '@lat': '4.37706' },
//     name: 'Culture Center',
//     locatieCode: '38',
//     picture: culture,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Mewtwo',
//     image: mewtwo,
//     isUnlocked: false,
//     instruction: 'Visit Chemical Engineering to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2628 BL',
//       straat: 'Julianalaan',
//       huisnummer: '136',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '52.00433', '@lat': '4.36836' },
//     name: 'Chemical Engineering',
//     locatieCode: '12',
//     picture: chemical,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Chansey',
//     image: chansey,
//     isUnlocked: false,
//     instruction: 'Visit Electrical Engineering to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2628 CD',
//       straat: 'Mekelweg',
//       huisnummer: '4',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '51.99903', '@lat': '4.37323' },
//     name: 'Electrical Engineering, Mathematics and Computer Sciences',
//     locatieCode: '36',
//     picture: ewi,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Burbasaur',
//     image: burbasaur,
//     isUnlocked: false,
//     instruction: 'Visit Facility Management & Real Estate to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2628 CE',
//       straat: 'Landbergstraat',
//       huisnummer: '8',
//       plaats: 'Delft',
//     },
//     name: 'Facility Management & Real Estate',
//     locatieCode: '30b',
//     picture: facility,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Alakazam',
//     image: alakazam,
//     isUnlocked: false,
//     instruction: 'Visit Industrial Design Engineering to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2628 CE',
//       straat: 'Landbergstraat',
//       huisnummer: '15',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '52.001622', '@lat': '4.370026' },
//     name: 'Industrial Design Engineering',
//     locatieCode: '32',
//     picture: io,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Wigglytuff',
//     image: wigglytuff,
//     isUnlocked: false,
//     instruction: 'Visit Education & Student Affairs to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2628 BX',
//       straat: 'Jaffalaan',
//       huisnummer: '9a',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '52.00277', '@lat': '4.37103' },
//     name: 'Education & Student Affairs',
//     locatieCode: '30a',
//     picture: education,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Vileplume',
//     image: vileplume,
//     isUnlocked: false,
//     instruction: 'Visit Mechanical, Maritime and Materials Engineering to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2628 CD',
//       straat: 'Mekelweg',
//       huisnummer: '2',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '52.000973', '@lat': '4.37196' },
//     name: 'Mechanical, Maritime and Materials Engineering',
//     locatieCode: '34',
//     picture: mechanical,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Psyduck',
//     image: psyduck,
//     isUnlocked: false,
//     instruction: 'Visit Physical and Chemical Technology to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2628 BW',
//       straat: 'Prins Bernhardlaan',
//       huisnummer: '6',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '52.0035', '@lat': '4.3703' },
//     name: 'Physical and Chemical Technology',
//     locatieCode: '15',
//     picture: physical,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Arcanine',
//     image: arcanine,
//     isUnlocked: false,
//     instruction: 'Visit Sports Center to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2628 CB',
//       straat: 'Leeghwaterstraat',
//       huisnummer: '39',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '51.9995', '@lat': '4.37108' },
//     name: 'Process & Energy Laboratory',
//     locatieCode: '34b',
//     picture: process,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Poliwhirl',
//     image: poliwhirl,
//     isUnlocked: false,
//     instruction: 'Visit Technology, Policy and Management to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2628 CD',
//       straat: 'Mekelweg',
//       huisnummer: '8',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '51.99536', '@lat': '4.37594' },
//     name: 'Sport Center',
//     locatieCode: '37',
//     picture: sport,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Chikorita',
//     image: chikorita,
//     isUnlocked: false,
//     instruction: 'Visit TU Delft Library to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2628 BX',
//       straat: 'Jaffalaan',
//       huisnummer: '5',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '52.002496', '@lat': '4.369415' },
//     name: 'Technology, Policy and Management',
//     locatieCode: '31',
//     picture: tpm,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Rapidash',
//     image: rapidash,
//     isUnlocked: false,
//     instruction: 'Visit The Fellowship to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2628 ZC',
//       straat: 'Prometheusplein',
//       huisnummer: '1',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '52.00262', '@lat': '4.37524' },
//     name: 'TU Delft Library',
//     locatieCode: '21',
//     picture: library,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
//   {
//     type: 'site',
//     uuid: '01122334-4556-6778-899a-abbccddeeff0',
//     major: 2,
//     minor: 772,
//     achievementName: 'Gyarados',
//     image: gyarados,
//     isUnlocked: false,
//     instruction: 'Visit Process & Energy Laboratory to unlock this sticker!',
//     feedback: 'Congratulations! You have unlocked this sticker!',
//     address: {
//       postcode: '2629 HS',
//       straat: 'Kluyverweg',
//       huisnummer: '5',
//       plaats: 'Delft',
//     },
//     gpscoordinaten: { '@lon': '51.99065', '@lat': '4.37756' },
//     name: 'The Fellowship',
//     locatieCode: '66',
//     picture: fellowship,
//     info:
//       'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
//   },
// ];

export const currentPokemon = [
  {
    achievementName: 'Ivysaur',
    image: ivysaur,
    isUnlocked: true,
    instruction: 'Visit Achitecture and the Built Environment to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
  {
    achievementName: 'Slowpoke',
    image: slowpoke,
    isUnlocked: true,
    instruction: 'Visit Applied Science to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
  {
    achievementName: 'Charmanda',
    image: charmanda,
    isUnlocked: true,
    instruction: 'Visit Aerospace Engineering to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
  {
    achievementName: 'Charmeleon',
    image: charmeleon,
    isUnlocked: true,
    instruction: 'Visit Applied Physics to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
  {
    achievementName: 'Charizard',
    image: charizard,
    isUnlocked: true,
    instruction: 'Visit Biotechnology to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
  {
    achievementName: 'Squirtle',
    image: squirtle,
    isUnlocked: true,
    instruction: 'Visit Civil Engineering and Geosciences to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
  {
    achievementName: 'Warturtle',
    image: warturtle,
    isUnlocked: true,
    instruction: 'Visit Culture Center to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
  {
    achievementName: 'Mewtwo',
    image: mewtwo,
    isUnlocked: true,
    instruction: 'Visit Chemical Engineering to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
  {
    achievementName: 'Chansey',
    image: chansey,
    isUnlocked: true,
    instruction: 'Visit Electrical Engineering to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
  {
    achievementName: 'Burbasaur',
    image: burbasaur,
    isUnlocked: true,
    instruction: 'Visit Facility Management & Real Estate to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
  {
    achievementName: 'Alakazam',
    image: alakazam,
    isUnlocked: true,
    instruction: 'Visit Industrial Design Engineering to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
  {
    achievementName: 'Wigglytuff',
    image: wigglytuff,
    isUnlocked: true,
    instruction: 'Visit Education & Student Affairs to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
  {
    achievementName: 'Vileplume',
    image: vileplume,
    isUnlocked: true,
    instruction: 'Visit Mechanical, Maritime and Materials Engineering to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
  {
    achievementName: 'Psyduck',
    image: psyduck,
    isUnlocked: true,
    instruction: 'Visit Physical and Chemical Technology to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
  {
    achievementName: 'Arcanine',
    image: arcanine,
    isUnlocked: true,
    instruction: 'Visit Sports Center to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
  {
    achievementName: 'Poliwhirl',
    image: poliwhirl,
    isUnlocked: true,
    instruction: 'Visit Technology, Policy and Management to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
  {
    achievementName: 'Chikorita',
    image: chikorita,
    isUnlocked: true,
    instruction: 'Visit TU Delft Library to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
  {
    achievementName: 'Rapidash',
    image: rapidash,
    isUnlocked: true,
    instruction: 'Visit The Fellowship to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
  {
    achievementName: 'Gyarados',
    image: gyarados,
    isUnlocked: true,
    instruction: 'Visit Process & Energy Laboratory to unlock this sticker!',
    feedback: 'Congratulations! You have unlocked this sticker!',
  },
];

export const sites = [
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 772,
    minor: 2,
    address: {
      postcode: '2628 CC',
      straat: 'Mekelweg',
      huisnummer: '5',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '52.0021', '@lat': '4.37325' },
    name: 'Aula Conference Centre',
    locatieCode: '20',
    picture: aula,
    info:
      'De combinatie van een Technische Universiteit, een gezellige oude stad, een goede bereikbaarheid en een perfecte outillage, maakt het Aula Congrescentrum een uiterst geschikte locatie voor congressen en andere wetenschappelijke of culturele bijeenkomsten.Het Aula Congrescentrum beschikt over 12 zalen van verschillende grootte, geschikt voor 10 tot 1200 personen. De zeer ruime Foyer, de verschillende vides en de entreehal met ontvangstbalie, maken het Aula Congrescentrum tot een unieke locatie.',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 258,
    minor: 772,
    name: 'Architecture and the Built Environment',
    address: {
      postcode: '2628 BL',
      straat: 'Julianalaan',
      huisnummer: '132-134',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '52.005696', '@lat': '4.370439' },
    locatieCode: '08',
    picture: architecture,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2,
    minor: 772,
    address: {
      postcode: '2629 HZ',
      straat: 'Van Der Maasweg',
      huisnummer: '9',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '4.379922', '@lat': '51.989124' },
    name: 'Applied Sciences',
    locatieCode: '58',
    picture: appliedsciences,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2,
    minor: 772,
    address: {
      postcode: '2629 HS',
      straat: 'Kluyverweg',
      huisnummer: '1',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '51.989923', '@lat': '4.375549' },
    name: 'Aerospace Engineering',
    locatieCode: '62',
    picture: aerospace,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2,
    minor: 772,
    address: {
      postcode: '2628 CJ',
      straat: 'Lorentzweg',
      huisnummer: '1',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '52.000912', '@lat': '4.37402' },
    name: 'Applied Physics',
    locatieCode: '22',
    picture: appliedphysics,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2,
    minor: 772,
    address: {
      postcode: '2628 BC',
      straat: 'Julianalaan',
      huisnummer: '67',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '52.00856', '@lat': '4.37129' },
    name: 'Biotechnology',
    locatieCode: '05',
    picture: biotechnology,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2,
    minor: 772,
    address: {
      postcode: '2628 CN',
      straat: 'Stevinweg',
      huisnummer: '1',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '51.99913', '@lat': '4.37595' },
    name: 'Civil Engineering and Geosciences',
    locatieCode: '23',
    picture: civil,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2,
    minor: 772,
    address: {
      postcode: '2628 CD',
      straat: 'Mekelweg',
      huisnummer: '10',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '51.9954', '@lat': '4.37706' },
    name: 'Culture Center',
    locatieCode: '38',
    picture: culture,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2,
    minor: 772,
    address: {
      postcode: '2628 BL',
      straat: 'Julianalaan',
      huisnummer: '136',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '52.00433', '@lat': '4.36836' },
    name: 'Chemical Engineering',
    locatieCode: '12',
    picture: chemical,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2,
    minor: 772,
    address: {
      postcode: '2628 CD',
      straat: 'Mekelweg',
      huisnummer: '4',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '51.99903', '@lat': '4.37323' },
    name: 'Electrical Engineering, Mathematics and Computer Sciences',
    locatieCode: '36',
    picture: ewi,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2,
    minor: 772,
    address: {
      postcode: '2628 CE',
      straat: 'Landbergstraat',
      huisnummer: '8',
      plaats: 'Delft',
    },
    name: 'Facility Management & Real Estate',
    locatieCode: '30b',
    picture: facility,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2,
    minor: 772,
    address: {
      postcode: '2628 CE',
      straat: 'Landbergstraat',
      huisnummer: '15',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '52.001622', '@lat': '4.370026' },
    name: 'Industrial Design Engineering',
    locatieCode: '32',
    picture: io,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2,
    minor: 772,
    address: {
      postcode: '2628 BX',
      straat: 'Jaffalaan',
      huisnummer: '9a',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '52.00277', '@lat': '4.37103' },
    name: 'Education & Student Affairs',
    locatieCode: '30a',
    picture: education,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2,
    minor: 772,
    address: {
      postcode: '2628 CD',
      straat: 'Mekelweg',
      huisnummer: '2',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '52.000973', '@lat': '4.37196' },
    name: 'Mechanical, Maritime and Materials Engineering',
    locatieCode: '34',
    picture: mechanical,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2,
    minor: 772,
    address: {
      postcode: '2628 BW',
      straat: 'Prins Bernhardlaan',
      huisnummer: '6',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '52.0035', '@lat': '4.3703' },
    name: 'Physical and Chemical Technology',
    locatieCode: '15',
    picture: physical,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2,
    minor: 772,
    address: {
      postcode: '2628 CB',
      straat: 'Leeghwaterstraat',
      huisnummer: '39',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '51.9995', '@lat': '4.37108' },
    name: 'Process & Energy Laboratory',
    locatieCode: '34b',
    picture: process,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2,
    minor: 772,
    address: {
      postcode: '2628 CD',
      straat: 'Mekelweg',
      huisnummer: '8',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '51.99536', '@lat': '4.37594' },
    name: 'Sport Center',
    locatieCode: '37',
    picture: sport,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2,
    minor: 772,
    address: {
      postcode: '2628 BX',
      straat: 'Jaffalaan',
      huisnummer: '5',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '52.002496', '@lat': '4.369415' },
    name: 'Technology, Policy and Management',
    locatieCode: '31',
    picture: tpm,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2,
    minor: 772,
    address: {
      postcode: '2628 ZC',
      straat: 'Prometheusplein',
      huisnummer: '1',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '52.00262', '@lat': '4.37524' },
    name: 'TU Delft Library',
    locatieCode: '21',
    picture: library,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
  {
    uuid: '01122334-4556-6778-899a-abbccddeeff0',
    major: 2,
    minor: 772,
    address: {
      postcode: '2629 HS',
      straat: 'Kluyverweg',
      huisnummer: '5',
      plaats: 'Delft',
    },
    gpscoordinaten: { '@lon': '51.99065', '@lat': '4.37756' },
    name: 'The Fellowship',
    locatieCode: '66',
    picture: fellowship,
    info:
      'The Faculty of Architecture and the Built Environment at TU Delft (Dutch: Faculteit Bouwkunde; abbr. BK ) is the largest faculty of the university with around 2900 students. It is also one of the top faculties of the TU Delft and was ranked 3rd in the world’s top universities for architecture & built environment in the QS World University Rankings by Subject 2015, following the Massachusetts Institute of Technology (MIT) and University College London (UCL).',
  },
];

export const events = [
  {
    name: 'Latitud Presents 1',
    address: {
      postcode: '2628 CD',
      straat: 'Mekelweg',
      huisnummer: '8',
      plaats: 'Delft',
    },
    locatieCode: '38',
    start: '21:00 on Friday, 16/06/2017',
    end: '03:00 on Sartuday, 17/06/2017',
    cost: '8.00 euro',
    picture: event01,
    description:
      "DJ Nika will be playing for us at our Carnaval! He's a half Fench, half Nicaraguan DJ with more than 15k followers and he is coming from his home-base in Switzerland just to play for us... In Delft! Come and experience such art resulting from the mix of two awesome worlds such as Nicaragua and France!",
  },
  {
    name: 'Latitud Presents 2',
    address: {
      postcode: '2628 CD',
      straat: 'Mekelweg',
      huisnummer: '8',
      plaats: 'Delft',
    },
    locatieCode: '38',
    start: '21:00 on Friday, 16/06/2017',
    end: '03:00 on Sartuday, 17/06/2017',
    cost: '8.00 euro',
    picture: event01,
    description:
      "DJ Nika will be playing for us at our Carnaval! He's a half Fench, half Nicaraguan DJ with more than 15k followers and he is coming from his home-base in Switzerland just to play for us... In Delft! Come and experience such art resulting from the mix of two awesome worlds such as Nicaragua and France!",
  },
  {
    name: 'Latitud Presents 3',
    address: {
      postcode: '2628 CD',
      straat: 'Mekelweg',
      huisnummer: '8',
      plaats: 'Delft',
    },
    locatieCode: '38',
    start: '21:00 on Friday, 16/06/2017',
    end: '03:00 on Sartuday, 17/06/2017',
    cost: '8.00 euro',
    picture: event01,
    description:
      "DJ Nika will be playing for us at our Carnaval! He's a half Fench, half Nicaraguan DJ with more than 15k followers and he is coming from his home-base in Switzerland just to play for us... In Delft! Come and experience such art resulting from the mix of two awesome worlds such as Nicaragua and France!",
  },
  {
    name: 'Latitud Presents 4',
    address: {
      postcode: '2628 CD',
      straat: 'Mekelweg',
      huisnummer: '8',
      plaats: 'Delft',
    },
    locatieCode: '38',
    start: '21:00 on Friday, 16/06/2017',
    end: '03:00 on Sartuday, 17/06/2017',
    cost: '8.00 euro',
    picture: event01,
    description:
      "DJ Nika will be playing for us at our Carnaval! He's a half Fench, half Nicaraguan DJ with more than 15k followers and he is coming from his home-base in Switzerland just to play for us... In Delft! Come and experience such art resulting from the mix of two awesome worlds such as Nicaragua and France!",
  },
  {
    name: 'Latitud Presents 5',
    address: {
      postcode: '2628 CD',
      straat: 'Mekelweg',
      huisnummer: '8',
      plaats: 'Delft',
    },
    locatieCode: '38',
    start: '21:00 on Friday, 16/06/2017',
    end: '03:00 on Sartuday, 17/06/2017',
    cost: '8.00 euro',
    picture: event01,
    description:
      "DJ Nika will be playing for us at our Carnaval! He's a half Fench, half Nicaraguan DJ with more than 15k followers and he is coming from his home-base in Switzerland just to play for us... In Delft! Come and experience such art resulting from the mix of two awesome worlds such as Nicaragua and France!",
  },
  {
    name: 'Latitud Presents 6',
    address: {
      postcode: '2628 CD',
      straat: 'Mekelweg',
      huisnummer: '8',
      plaats: 'Delft',
    },
    locatieCode: '38',
    start: '21:00 on Friday, 16/06/2017',
    end: '03:00 on Sartuday, 17/06/2017',
    cost: '8.00 euro',
    picture: event01,
    description:
      "DJ Nika will be playing for us at our Carnaval! He's a half Fench, half Nicaraguan DJ with more than 15k followers and he is coming from his home-base in Switzerland just to play for us... In Delft! Come and experience such art resulting from the mix of two awesome worlds such as Nicaragua and France!",
  },
];

export const me = {
  gender: 'female',
  name: {
    title: 'ms',
    first: 'qiaoqiao',
    last: 'li',
  },
  location: {
    street: 'Hendrik Tollensstraat',
    city: 'Delft',
    state: 'the Netherlands',
    postcode: '2624 BJ',
  },
  email: 'q.li-5@student.tudelft.nl',
  login: {
    username: 'qiaoqiaoli',
    password: '123456789',
    salt: '9Ffpa2So',
    md5: '198b5f56ee13576e3d707f632122d2ac',
    sha1: '8f002ab67dfb4d8a5479f88bef403f554e73d537',
    sha256: '224ded287fffe096a47bd8ef6080ab6730106bf31e6ccf8fa87f34b4e063c66e',
  },
  dob: '1993-12-26',
  registered: '2011-06-19 07:37:58',
  phone: '06-8231-8055',
  cell: '0682-318-055',
  id: {
    name: 'TFN',
    value: '089149818',
  },
  picture: {
    large: 'https://avatars2.githubusercontent.com/u/17089306?v=3&s=460',
    medium: 'https://randomuser.me/api/portraits/med/women/43.jpg',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/women/43.jpg',
  },
  nat: 'CN',
};
