# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'gamifiedCampusEngagement' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gamifiedCampusEngagement
  pod 'Firebase/Core'

  # target 'gamifiedCampusEngagementTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
